{% set version = '1.1.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qgg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qgg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qgg/qgg_{{ version }}.tar.gz
  sha256: dff06a1f4684622a4e60f617758254d25210f5081d814bc143906cea8b297a19

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-mcmcpack                   # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpp >=1.0.5               # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-coda                       # [build_platform != target_platform]
    - r-corpcor                    # [build_platform != target_platform]
    - r-data.table                 # [build_platform != target_platform]
    - r-statmod                    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-rcpp >=1.0.5
    - r-rcpparmadillo
    - r-coda
    - r-corpcor
    - r-data.table
    - r-statmod
  run:
    - r-base
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-rcpp >=1.0.5
    - r-rcpparmadillo
    - r-coda
    - r-corpcor
    - r-data.table
    - r-statmod

test:
  commands:
    - $R -e "library('qgg')"           # [not win]
    - "\"%R%\" -e \"library('qgg')\""  # [win]

about:
  home: https://github.com/psoerensen/qgg
  license: GPL-3.0-only
  summary: 'Provides an infrastructure for efficient processing of large-scale genetic and phenotypic
    data including core functions for: 1) fitting linear mixed models, 2) constructing
    marker-based genomic relationship matrices, 3) estimating genetic parameters (heritability
    and correlation), 4) performing genomic prediction and genetic risk profiling, and
    5) single or multi-marker association analyses. Rohde et al. (2019) <doi:10.1101/503631>.'
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - psoerensen

# Package: qgg
# Type: Package
# Title: Statistical Tools for Quantitative Genetic Analyses
# Version: 1.1.6
# Date: 2024-12-13
# Authors@R: c(person("Peter", "Soerensen", email = "peter.sorensen@r-qgg.org", role = c("aut", "cre")), person("Palle", "Duun Rohde", email = "palle.d.rohde@mbg.au.dk", role = "aut"), person("Izel", "Fourie Soerensen", email = "izel.sorensen@gmail.com", role = "aut"))
# Maintainer: Peter Soerensen <peter.sorensen@r-qgg.org>
# Description: Provides an infrastructure for efficient processing of large-scale genetic and phenotypic data including core functions for: 1) fitting linear mixed models, 2) constructing marker-based genomic relationship matrices, 3) estimating genetic parameters (heritability and correlation), 4) performing genomic prediction and genetic risk profiling, and 5) single or multi-marker association analyses. Rohde et al. (2019) <doi:10.1101/503631>.
# License: GPL-3
# Encoding: UTF-8
# Depends: R (>= 3.3.0)
# Imports: Rcpp (>= 1.0.5), data.table, parallel, statmod, stats, MCMCpack, MASS, coda, corpcor, Matrix, methods
# LinkingTo: Rcpp, RcppArmadillo
# RoxygenNote: 7.3.2
# URL: https://github.com/psoerensen/qgg
# BugReports: https://github.com/psoerensen/qgg/issues
# NeedsCompilation: yes
# Packaged: 2024-12-15 16:03:53 UTC; au223366
# Author: Peter Soerensen [aut, cre], Palle Duun Rohde [aut], Izel Fourie Soerensen [aut]
# Repository: CRAN
# Date/Publication: 2024-12-16 16:50:02 UTC
